npm_install:
  stage: npm_install
  image: ${NODE_IMAGE}
  script:
    - npm set registry ${SOARIZON_REGISTRY}
    - npm install
  artifacts:
    untracked: true
    paths:
      - node_modules/
#   tags: 
#     - autoscale_premium
